site_name: NOGI - Developer Docs
theme:
  name: material
plugins:
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
  - render_swagger
  - search
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - assets/mkdocs-oad-v1.0.4.css